# Generated by Django 5.2.6 on 2025-10-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание товара')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-адрес')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='catalog', verbose_name='Изображение товара')),
            ],
        ),
    ]
