# Generated by Django 5.2.6 on 2025-10-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_plant_created_at_plant_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-адрес')),
                ('image', models.ImageField(upload_to='catalog/categories', verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name': 'Растение', 'verbose_name_plural': 'Растения'},
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(upload_to='catalog/plants', verbose_name='Изображение товара'),
        ),
    ]
