# Generated by Django 5.2.6 on 2025-10-13 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_alter_plant_options_alter_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='catalog.category'),
        ),
    ]
