# Generated by Django 5.2.6 on 2026-01-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_plant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='popularity',
            field=models.PositiveIntegerField(default=0, verbose_name='Популярность товара'),
        ),
    ]
