# Generated by Django 5.2.6 on 2026-01-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_plant_popularity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='popularity',
            new_name='views_count',
        ),
    ]
