# Generated by Django 5.2.10 on 2026-02-03 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_popularity_plant_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='sale',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(upload_to='catalog/plants', verbose_name='Количество посещений'),
        ),
    ]
