# Generated by Django 5.2.10 on 2026-02-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_plant_sale_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sale',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Скидка в процентах'),
        ),
    ]
