# Generated by Django 5.2.10 on 2026-02-04 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_plant_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sale',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Скидка в процентах'),
        ),
    ]
