# Generated by Django 5.2.10 on 2026-02-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_plant_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='stock_count',
            field=models.IntegerField(default=0, verbose_name='Количество товаров'),
        ),
    ]
