# Generated by Django 5.2.10 on 2026-02-04 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_plant_stock_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='stock_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество товаров'),
        ),
    ]
