# Generated by Django 5.2.10 on 2026-02-04 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_plant_stock_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0, 'Price cannot be lt 0')], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sale',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0, 'Discount cannot be lt 0'), django.core.validators.MaxValueValidator(100.0, 'Discount cannot be gt 100')], verbose_name='Скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='stock_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Stock cannot be lt 0')], verbose_name='Количество товаров'),
        ),
    ]
