# Generated by Django 5.2.10 on 2026-02-04 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_plant_price_alter_plant_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0, 'Цена не может быть меньше 0')], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sale',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0, 'Скидка не может быть меньше 0'), django.core.validators.MaxValueValidator(100.0, 'Скидка не может быть больше 100')], verbose_name='Скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='stock_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Количество товара не может быть меньше 0')], verbose_name='Количество товара'),
        ),
    ]
