# Generated by Django 5.2.10 on 2026-02-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_plant_price_alter_plant_sale_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(condition=models.Q(('sale__gte', 0)), name='sale_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(condition=models.Q(('sale__lte', 100)), name='sale_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(condition=models.Q(('stock_count__gte', 0)), name='stock_count_gte_0'),
        ),
    ]
