# Generated by Django 5.2.6 on 2026-01-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user_profile/default.jpg', upload_to='user_profile/profile_images/', verbose_name='Изображение профиля'),
        ),
    ]
