# Generated by Django 5.2.6 on 2026-01-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='user_profile/profile_images/', verbose_name='Изображение профиля'),
        ),
    ]
