# Generated by Django 5.2.10 on 2026-02-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_profile_options_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_profile/profile_images/', verbose_name='Изображение профиля'),
        ),
    ]
